spring:
  application:
    name: domain
  data:
    mongodb:
      database: banking-db
server:
  port: 8081

spring.cloud.stream:
  kafka.binder:
    autoCreateTopics: true
  bindings:
    request_channel:
      destination: request-channel
      content-type: application/json
      binder: kafka
    reply_channel:
      destination: reply-channel
      content-type: application/json
      binder: kafka
