version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - db_mongo_data:/data/db

  rest-api:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: banking-rest-api/Dockerfile
      network: host
    depends_on:
      - kafka
    links:
      - kafka:kafka
    ports:
      - 8080:8080

  domain:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: banking-domain/Dockerfile
      network: host
    depends_on:
      - kafka
      - db
    links:
      - kafka:kafka
    ports:
      - 8081:8081

volumes:
  db_mongo_data:
    driver: local